---
title: "SpecDAL WF vs Spectrolab WF"
author: "Kyle Kovach"
date: "12/17/2020"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
require(reshape2)
require(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
wd="F:/PostDoc/ABoVE"
```

```{r cars,include=FALSE,echo=FALSE}
tspec=read.csv(paste0(wd,"/tdryspec.csv"),head=T,check.names=FALSE)
kspec=read.csv(paste0(wd,"/kdryspecJCours.csv"),head=T,check.names=FALSE)
tspec=tspec[order(tspec$sample_name),]
kspec=kspec[order(kspec$sample_name),]
summary(tspec$sample_name==kspec$sample_name)
```

```{r pressure, echo=FALSE}
newspec=tspec[,-1]-kspec[,-1]
newspec=abs(newspec)
means=colMeans(newspec)
plot(means,xaxt = "n",xlab="band",ylab="MAD (% ref)",main="SpecDAL vs Spectrolab extracted and jump corrected spectra (using ABoVE 2019 dry spectra)")
axis(1, at=seq(150, 2151, by=500), labels=seq(500,2500, by=500))
```

## Plots

```{r}
tspec_sub=tspec[3555,]
tspec_sub$sample_name="SpecDAL"
kspec_sub=kspec[3555,]
kspec_sub$sample_name="Spectrolab"
combspec=rbind(tspec_sub,kspec_sub)
finalspec=melt(combspec, id.vars=c("sample_name"))

ggplot(finalspec, aes(x=as.numeric(variable), y=value, color=sample_name))+
  geom_line()+
  ggtitle("CHAR_021_DRIN_00000 Spectra")+
  ylab("value")+
  labs(color='Method')+
  theme_bw()+
  scale_x_continuous(name="band",
                     limits=c(0, 2151),
                     breaks=seq(150, 2151,by=500),
                     labels=seq(500,2500, by=500))
```
